//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVShow.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TVShow.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;shows&gt;
        ///  &lt;show&gt;
        ///      &lt;id&gt;1&lt;/id&gt;
        ///      &lt;name&gt;Dr House&lt;/name&gt;
        ///      &lt;favourite&gt;0&lt;/favourite&gt;
        ///  &lt;/show&gt;
        ///  &lt;show&gt;
        ///    &lt;id&gt;2&lt;/id&gt;
        ///    &lt;name&gt;Brooklyn Nine-Nine&lt;/name&gt;
        ///    &lt;favourite&gt;1&lt;/favourite&gt;
        ///  &lt;/show&gt;
        ///  &lt;show&gt;
        ///    &lt;id&gt;2&lt;/id&gt;
        ///    &lt;name&gt;The Simpsons&lt;/name&gt;
        ///    &lt;favourite&gt;0&lt;/favourite&gt;
        ///  &lt;/show&gt;
        ///  &lt;show&gt;
        ///    &lt;id&gt;3&lt;/id&gt;
        ///    &lt;name&gt;X-Files&lt;/name&gt;
        ///    &lt;favourite&gt;0&lt;/favourite&gt;
        ///  &lt;/show&gt;
        ///  &lt;show&gt;
        ///    &lt;id&gt;4&lt;/id&gt;
        ///    &lt;name&gt;ALF&lt;/name&gt;
        ///    &lt;favourite&gt;0&lt;/f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TVGuide {
            get {
                return ResourceManager.GetString("TVGuide", resourceCulture);
            }
        }
    }
}
